### ISSUE TITLE
visualiser plusieurs informations/événements sur une carte

### ISSUE THREAD

**Issue by Leoglme** [Leoglme/EpiTrip_Frontend#5]

**Comment by RousseauFlorian** [comment]
16/04/2024 09:40:19 - creation of the feature/5-visualiser-plusieurs-informationsvnements-sur-une-carte branch and branch link to issue 5 - RousseauFlorian

**Comment by RousseauFlorian** [comment]
16/04/2024 09:40:51 - create pull request branch feature/5-visualiser-plusieurs-informationsvnements-sur-une-carte to develop - RousseauFlorian. [PR #]()
